### ISSUE TITLE
Crash when setting visualizer bars to low numbers

### ISSUE THREAD

**Issue by WiseDragoon5374** [EVAST9919/lazer-sandbox#12]
With the latest release of osu!lazer (version 2022.810.2), the visualizer crashes upon setting the bar amount to a low number, by dragging the slider to the far left, with the error message:

```
An unhandled error has occurred.
System.ArgumentException: Statistics counter Pixels was attempted to be decremented via Add call. (Parameter 'amount')
at osu.Framework.Statistics.FrameStatistics.Add(StatisticsCounterType type, Int64 amount)
at osu.Framework.Graphics.Rendering.RendererExtensions.DrawQuad(IRenderer renderer, Texture texture, Quad vertexQuad, ColourInfo drawColour, Nullable`1 textureRect, Action`1 vertexAction, Nullable`1 inflationPercentage, Nullable`1 blendRangeOverride, Nullable`1 textureCoords)
at osu.Game.Rulesets.Sandbox.Screens.Visualizer.Components.Visualizers.Circular.BasicMusicVisualizerDrawable.BasicVisualizerDrawNode.DrawBar(Int32 index, Single data, Single spacing, Vector2 inflation, IRenderer renderer)
at osu.Game.Rulesets.Sandbox.Screens.Visualizer.Components.Visualizers.MusicVisualizerDrawable.VisualizerDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(IRenderer renderer)
at osu.Framework.Platform.GameHost.DrawFrame()
at osu.Framework.Threading.GameThread.processFrame()
```

This locks the visualizer forever, throwing the same error and crashing every time I open the visualizer now. In-game, the game plays two "notification" sounds and then stops. The music plays and the frame is stuck for a while, but then it fully exits and I have to relaunch.

**Comment by EVAST9919** [comment]
Should be fixed in the next lazer update (https://github.com/ppy/osu-framework/pull/5347)

**Comment by WiseDragoon5374** [comment]
Thanks!

**Comment by EVAST9919** [comment]
I'll leave this one open until it's actually fixed just in case

**Comment by WiseDragoon5374** [comment]
Sadly, the latest osu!lazer version (2022.816.0) still causes this crash. I'm assuming there's probably a way to reset the variable used for setting the visualizer bars, but I have no idea what that might be.

**Comment by EVAST9919** [comment]
Closing as potentially fixed
